import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The internal handbook is a flat, numbered set (01..09 + README index).
// Autogenerate the sidebar from the docs directory so file order drives it.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
